import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/src/components/NavBar";
import Timeline from "@/src/components/Timeline";
import { AuthProvider } from "../context/auth";
import LayoutWithSidebar from "@/src/components/LayoutWithSidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Twittor Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={inter.className}
        style={{ backgroundColor: "oklch(82.8% 0.111 230.318)" }}
      >
        <AuthProvider>
          <LayoutWithSidebar>{children}</LayoutWithSidebar>
        </AuthProvider>
      </body>
    </html>
  );
}
