import Post from "@/components/Post";
import Timeline from "@/components/Timeline";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>SNS Udemy</title>
        <meta name="description" content="Generated by next app" />
        <meta name="viewpoint" content="width-device-width,initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Timeline />
      </div>
    </>
  );
}
